config/routes.rb
require "heartbeat/application"

Rails.application.routes.draw do
  mount Heartbeat::Application, at: "/heartbeat"

  namespace :admin do
    root 'application#index'

    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
    resources :states, only: [:new, :create, :index] do
      member do
        get :make_default
      end
    end
  end

  namespace :api do
    namespace :v2 do
      mount API::V2::Tickets, at: "/projects/:project_id/tickets"
    end

    resources :projects, only: [] do
      resources :tickets
    end
  end

  devise_for :users
  root "projects#index"

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  resources :attachments, only: [:show, :new]

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :tags, uniq: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def remove
		@ticket = Ticket.find(params[:ticket_id])
		@tag = Tag.find(params[:id])
		authorize @ticket, :tag?

		@ticket.tags.destroy(@tag)
		head:ok
	end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<% if current_page?(action: 'new') || current_page?(action: 'edit') %>
	<%= f.input :tag_names, label: "Tags", hint: "separated by a space", input_html: { value: ticket.show_tags_in_edit } %>
<% else %>
	<%= f.input :tag_names, label: "Tags", hint: "separated by a space" %>
<% end %>

app/views/tags/_tag.html.erb
<div class="tag">
	<% if policy(ticket).tag? %>
	<%= link_to "<span></span>".html_safe, remove_ticket_tag_path(ticket, tag),
	method: :delete, remote: true, class: "remove", title: "remove" %>
	<% end %>
	
	<%= link_to tag.name, search_project_tickets_path(ticket.project,
		search: "tag:#{tag.name}") %>
</div>